export const data = [
    {
      id: "m5gr84i9",
      status: "Canceled",
      task: "task-001",
      title: "If we program the card,",
      level: "bug",
      priority: "High",
      date: "05/05/2024",
    },
    {
      id: "3u1reuv4",
      status: "✔ Todo",
      task: "task-002",
      title: "we can get to the IP capacitor through the haptic ",
      level: "feature  ",
      priority: "Low",
      date: "5/21/2024",
    },
    {
      id: "derv1ws0",
      status: "✔️Done",
      task: "task-003",
      title: "Generating the matrix won't do anything",
      level: "documentation",
      priority: "Medium",
      date: "6/05/2024",
    },
    {
      id: "5kma53ae",
      status: "success",
      task: "task-004",
      title: "we can get to the IP capacitor through the haptic",
      level: "enhancement",
      priority: "High",
      date: "8/05/2024",
    },
    {
      id: "bhqecj4p",
      status: "Medium",
      task: "task-005",
      title: "We need to program the auxiliary API port!",
      level: "documentation",
      priority: "High",
      date: "3/05/2024",
    },
    {
      id: "m5gr84i9",
      status: "Canceled",
      task: "task-001",
      title: "If we program the card,",
      level: "bug",
      priority: "High",
      date: "05/05/2024",
    },
    {
      id: "3u1reuv4",
      status: "Todo",
      task: "task-002",
      title: "we can get to the IP capacitor through the haptic ",
      level: "feature  ",
      priority: "Low",
      date: "5/21/2024",
    },
    {
      id: "derv1ws0",
      status: "✔️Done",
      task: "task-003",
      title: "Generating the matrix won't do anything",
      level: "documentation",
      priority: "Medium",
      date: "6/05/2024",
    },
    {
      id: "5kma53ae",
      status: "success",
      task: "task-004",
      title: "we can get to the IP capacitor through the haptic",
      level: "enhancement",
      priority: "High",
      date: "8/05/2024",
    },
    {
      id: "bhqecj4p",
      status: "Medium",
      task: "task-005",
      title: "We need to program the auxiliary API port!",
      level: "documentation",
      priority: "High",
      date: "3/05/2024",
    },
    {
      id: "m5gr84i9",
      status: "Canceled",
      task: "task-001",
      title: "If we program the card,",
      level: "bug",
      priority: "High",
      date: "05/05/2024",
    },
    {
      id: "3u1reuv4",
      status: "Todo",
      task: "task-002",
      title: "we can get to the IP capacitor through the haptic ",
      level: "feature  ",
      priority: "Low",
      date: "5/21/2024",
    },
    {
      id: "derv1ws0",
      status: "✔️Done",
      task: "task-003",
      title: "Generating the matrix won't do anything",
      level: "documentation",
      priority: "Medium",
      date: "6/05/2024",
    },
    {
      id: "5kma53ae",
      status: "success",
      task: "task-004",
      title: "we can get to the IP capacitor through the haptic",
      level: "enhancement",
      priority: "High",
      date: "8/05/2024",
    },
    {
      id: "bhqecj4p",
      status: "Medium",
      task: "task-005",
      title: "We need to program the auxiliary API port!",
      level: "documentation",
      priority: "High",
      date: "3/05/2024",
    },
    {
      id: "m5gr84i9",
      status: "Canceled",
      task: "task-001",
      title: "If we program the card,",
      level: "bug",
      priority: "High",
      date: "05/05/2024",
    },
    {
      id: "3u1reuv4",
      status: "Todo",
      task: "task-002",
      title: "we can get to the IP capacitor through the haptic ",
      level: "feature  ",
      priority: "Low",
      date: "5/21/2024",
    },
    {
      id: "derv1ws0",
      status: "✔ Done",
      task: "task-003",
      title: "Generating the matrix won't do anything",
      level: "documentation",
      priority: "Medium",
      date: "6/05/2024",
    },
    {
      id: "5kma53ae",
      status: "success",
      task: "task-004",
      title: "we can get to the IP capacitor through the haptic",
      level: "enhancement",
      priority: "High",
      date: "8/05/2024",
    },
    {
      id: "bhqecj4p",
      status: "Medium",
      task: "task-005",
      title: "We need to program the auxiliary API port!",
      level: "documentation",
      priority: "High",
      date: "3/05/2024",
    },
  ];