import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar/Navbar";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <Providers>
        <body className={`${inter.className} mx-auto w-full`}>
          <div className="mx-auto flex flex-col items-center w-full h-[138vh] relative">
            <Navbar />
            <Header />
          </div>
          <div className="max-w-screen-xl mx-auto flex flex-col items-center bg-violet-300 h-[200vh]">
            {children}
          </div>
        </body>
      </Providers>
    </html>
  );
}
